create table if not exists subscribed_customers (
  id text primary key,
  고객번호 text,
  모델명 text,
  계약일자 text,
  계약만료일자 text,
  예약일자 text,
  당월작업 text,
  최종작업내용 text,
  status text default '미분류',
  계약자구분 text,
  고객명_상호 text,
  사업자번호 text,
  전화번호 text,
  핸드폰번호 text,
  주소 text,
  설치처구분 text,
  설치자명 text,
  설치구분 text,
  설치전화번호 text,
  설치핸드폰번호 text,
  설치주소 text,
  설치시특이사항 text,
  현장메모 text,
  lat float8,
  lng float8,
  created_at timestamp with time zone default timezone('utc'::text, now())
);
